### ISSUE TITLE
vscode move-analyzer plugin error

### ISSUE THREAD

**Issue by lizhecome** [move-language/move-sui#3]
I install the lastest version of  move-analyzer ,when I save a move file, the popup is showed like this

  
![WechatIMG22496](https://github.com/user-attachments/assets/afa44bbf-ee44-40f2-885e-90510d6d5697)

and my Move.toml file like this
```toml
[package]
name = "animal_crossing"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

===something else=====
```
and I found everything goes well when I change the toml file like this

```toml
[package]
name = "animal_crossing"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
version = "0.0.1"
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]
```
**version = "0.0.1"** is the necessary？ or is it a bug？
PS：I use the cli to init the project.
